// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
// Copyright (c) 2025 Meta Platforms, Inc. and affiliates.
#ifndef __MEMCGSTAT_H
#define __MEMCGSTAT_H

enum memcg_item {
	/* node_stat_item's */
	USER_NR_INACTIVE_ANON,
	USER_NR_ACTIVE_ANON,
	USER_NR_INACTIVE_FILE,
	USER_NR_ACTIVE_FILE,
	USER_NR_UNEVICTABLE,
	USER_NR_SLAB_RECLAIMABLE_B,
	USER_NR_SLAB_UNRECLAIMABLE_B,
	USER_WORKINGSET_REFAULT_ANON,
	USER_WORKINGSET_REFAULT_FILE,
	USER_WORKINGSET_ACTIVATE_ANON,
	USER_WORKINGSET_ACTIVATE_FILE,
	USER_WORKINGSET_RESTORE_ANON,
	USER_WORKINGSET_RESTORE_FILE,
	USER_WORKINGSET_NODERECLAIM,
	USER_NR_ANON_MAPPED,
	USER_NR_FILE_MAPPED,
	USER_NR_FILE_PAGES,
	USER_NR_FILE_DIRTY,
	USER_NR_WRITEBACK,
	USER_NR_SHMEM,
	USER_NR_SHMEM_THPS,
	USER_NR_FILE_THPS,
	USER_NR_ANON_THPS,
	USER_NR_KERNEL_STACK_KB,
	USER_NR_PAGETABLE,
	USER_NR_SECONDARY_PAGETABLE,
	USER_NR_SWAPCACHE,
	USER_PGPROMOTE_SUCCESS,
	USER_PGDEMOTE_KSWAPD,
	USER_PGDEMOTE_DIRECT,
	USER_PGDEMOTE_KHUGEPAGED,
	USER_PGDEMOTE_PROACTIVE,
	USER_NR_HUGETLB,
	/* memcg_stat_items */
	USER_MEMCG_SWAP,
	USER_MEMCG_SOCK,
	USER_MEMCG_PERCPU_B,
	USER_MEMCG_VMALLOC,
	USER_MEMCG_KMEM,
	USER_MEMCG_ZSWAP_B,
	USER_MEMCG_ZSWAPPED,
};

#endif /* __MEMCGSTAT_H */
