// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
// Copyright (c) 2025 Meta Platforms, Inc. and affiliates.
#ifndef __MEMCGSTAT_H
#define __MEMCGSTAT_H

enum memcg_item {
	/* node_stat_item */
	USER_NR_ANON_MAPPED,
	USER_NR_FILE_PAGES,
	USER_NR_KERNEL_STACK_KB,
	USER_NR_SHMEM,
	USER_NR_FILE_MAPPED,
	USER_NR_FILE_DIRTY,
	USER_NR_WRITEBACK,
	USER_NR_FILE_THPS,
	USER_NR_ANON_THPS,
	USER_NR_INACTIVE_ANON,
	USER_NR_ACTIVE_ANON,
	USER_NR_INACTIVE_FILE,
	USER_NR_ACTIVE_FILE,
	USER_NR_UNEVICTABLE,
	USER_NR_SLAB_RECLAIMABLE_B,
	USER_NR_SLAB_UNRECLAIMABLE_B,
	USER_WORKINGSET_REFAULT_ANON,
	USER_WORKINGSET_REFAULT_FILE,
	USER_WORKINGSET_ACTIVATE_ANON,
	USER_WORKINGSET_ACTIVATE_FILE,
	USER_WORKINGSET_RESTORE_ANON,
	USER_WORKINGSET_RESTORE_FILE,
	USER_WORKINGSET_NODERECLAIM,
	/* memcg_stat_item */
	USER_MEMCG_KMEM,
	USER_MEMCG_SOCK,
	USER_MEMCG_ZSWAP_B,
	USER_MEMCG_ZSWAPPED,
	/* vm_event_item */
	USER_PGSCAN_KSWAPD,
	USER_PGSCAN_DIRECT,
	USER_PGSCAN_KHUGEPAGED,
	USER_PGSCAN_PROACTIVE,
	USER_PGSTEAL_KSWAPD,
	USER_PGSTEAL_DIRECT,
	USER_PGSTEAL_KHUGEPAGED,
	USER_PGSTEAL_PROACTIVE,
	USER_PGFAULT,
	USER_PGMAJFAULT,
	USER_PGREFILL,
	USER_PGACTIVATE,
	USER_PGDEACTIVATE,
	USER_PGLAZYFREE,
	USER_PGLAZYFREED,
	USER_THP_FAULT_ALLOC,
	USER_THP_COLLAPSE_ALLOC,

	USER_ITEM_COUNT
};

#endif /* __MEMCGSTAT_H */
